/**
 * 초기 샘플 데이터 - 실제 접근 가능한 URL 사용
 */
const { insertArticle, db } = require('../models/database');

function getRecentDate(daysAgo, hoursAgo) {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(d.getHours() - hoursAgo);
  // KST = UTC+9: 샘플 데이터는 KST 기준으로 생성
  const kst = new Date(d.getTime() + 9 * 60 * 60 * 1000);
  return kst.toISOString().replace('T', ' ').substring(0, 19);
}

const sampleArticles = [
  {
    title: '중대재해처벌법 시행 이후 산업재해 사망자 감소 추세',
    content: '고용노동부에 따르면 중대재해처벌법 시행 이후 산업재해 사망자 수가 지속적으로 감소하고 있는 것으로 나타났다.',
    summary: '중대재해처벌법 시행 이후 산업재해 사망자가 지속 감소하는 추세를 보이고 있다.',
    url: 'https://www.moel.go.kr/news/enews/report/enewsView.do',
    source: '고용노동부',
    source_category: '정부기관',
    category: '중대재해',
    keywords: '중대재해처벌법,산업재해,사망자',
    author: '고용노동부',
    image_url: null,
    published_at: getRecentDate(0, 2),
  },
  {
    title: '2025년 산업재해 현황 분석 보고서 발간',
    content: '안전보건공단은 2025년 산업재해 현황을 분석한 보고서를 발간했다고 밝혔다.',
    summary: '2025년 산업재해 현황 및 통계를 분석한 연간 보고서가 발간됐다.',
    url: 'https://www.kosha.or.kr/kosha/data/mSHB.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '산업재해·안전',
    keywords: '산업재해,통계,안전보건공단',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(0, 4),
  },
  {
    title: '산업안전보건법 시행규칙 개정 – 안전보건교육 시간 확대',
    content: '고용노동부는 산업안전보건법 시행규칙을 개정하여 신규 채용자 안전보건교육 시간을 확대했다.',
    summary: '산업안전보건법 시행규칙 개정으로 안전보건교육 시간이 강화됐다.',
    url: 'https://www.law.go.kr/lsSc.do?menuId=1&subMenuId=15&tabMenuId=81&query=%EC%82%B0%EC%97%85%EC%95%88%EC%A0%84%EB%B3%B4%EA%B1%B4%EB%B2%95%EB%B2%95',
    source: '법제처(산업안전보건)',
    source_category: '법령',
    category: '법령·제도',
    keywords: '산업안전보건법,시행규칙,안전교육,개정',
    author: '법제처',
    image_url: null,
    published_at: getRecentDate(1, 0),
  },
  {
    title: '정부, 건설현장 추락사고 예방 종합대책 발표',
    content: '고용노동부는 건설현장에서 빈번하게 발생하는 추락사고를 예방하기 위한 종합대책을 발표했다.',
    summary: '건설현장 추락사고 예방을 위한 종합대책이 발표됐다.',
    url: 'https://www.korea.kr/news/pressReleaseView.do?newsId=156400000',
    source: '정책브리핑',
    source_category: '정부기관',
    category: '산업재해·안전',
    keywords: '건설현장,추락사고,안전망,산업재해',
    author: '정책브리핑',
    image_url: null,
    published_at: getRecentDate(1, 3),
  },
  {
    title: '유해화학물질 노출 기준 강화 고시 개정 예고',
    content: '고용노동부가 유해화학물질 노출 기준을 강화하는 고시 개정을 예고했다. 벤젠, 포름알데히드 등 17종의 허용 기준치가 낮아질 예정이다.',
    summary: '벤젠 등 17종 유해화학물질의 허용 노출 기준이 강화될 예정이다.',
    url: 'https://www.moel.go.kr/news/enews/report/enewsList.do',
    source: '고용노동부',
    source_category: '정부기관',
    category: '직업보건·화학',
    keywords: '화학물질,유해화학물질,노출기준,고시',
    author: '고용노동부',
    image_url: null,
    published_at: getRecentDate(2, 1),
  },
  {
    title: '직업성 암 예방 관리 체계 강화 방안 마련',
    content: '고용노동부와 안전보건공단은 직업성 암 발생 예방 및 관리 체계를 강화하기 위한 방안을 마련했다.',
    summary: '직업성 암 예방 및 관리 체계 강화 방안이 마련됐다.',
    url: 'https://www.kosha.or.kr/kosha/news/pressRelease.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '직업보건·화학',
    keywords: '직업성암,직업병,예방,안전보건',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(2, 4),
  },
  {
    title: '소규모 사업장 안전보건관리체계 구축 지원 확대',
    content: '안전보건공단은 50인 미만 소규모 사업장을 대상으로 안전보건관리체계 구축을 지원하는 사업을 대폭 확대한다.',
    summary: '소규모 사업장 안전보건관리체계 구축 지원이 확대된다.',
    url: 'https://www.kosha.or.kr/kosha/business/oshMgSysSupport.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '기관동향',
    keywords: '안전보건관리체계,중소기업,지원사업,KOSHA',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(3, 0),
  },
  {
    title: '근골격계질환 예방 관리 지침 전면 개정',
    content: '고용노동부는 근골격계질환 예방 관리 지침을 13년 만에 전면 개정했다.',
    summary: '13년만에 근골격계질환 예방 관리 지침이 전면 개정됐다.',
    url: 'https://www.moel.go.kr/info/lawinfo/instruction/view.do',
    source: '고용노동부',
    source_category: '정부기관',
    category: '직업보건·화학',
    keywords: '근골격계질환,예방,지침,개정',
    author: '고용노동부',
    image_url: null,
    published_at: getRecentDate(3, 3),
  },
  {
    title: '화학물질관리법 주요 개정 사항 안내',
    content: '환경부는 화학물질관리법 개정에 따른 주요 변경 사항을 안내했다.',
    summary: '화학물질관리법 개정으로 취급시설 안전관리 기준이 강화됐다.',
    url: 'https://www.law.go.kr/lsSc.do?menuId=1&subMenuId=15&tabMenuId=81&query=%ED%99%94%ED%95%99%EB%AC%BC%EC%A7%88%EA%B4%80%EB%A6%AC%EB%B2%95',
    source: '법제처(화학물질)',
    source_category: '법령',
    category: '직업보건·화학',
    keywords: '화학물질관리법,개정,취급시설',
    author: '법제처',
    image_url: null,
    published_at: getRecentDate(4, 0),
  },
  {
    title: 'AI·IoT 기반 스마트 안전관리 시스템 보급 확대',
    content: '안전보건공단은 AI와 IoT 기술을 활용한 스마트 안전관리 시스템 보급을 확대한다.',
    summary: 'AI·IoT 기반 스마트 안전관리 시스템이 500개 사업장에 무상 보급된다.',
    url: 'https://www.kosha.or.kr/kosha/business/smartSafety.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '기관동향',
    keywords: 'AI,IoT,스마트안전,안전보건공단',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(4, 2),
  },
  {
    title: '외국인 근로자 산업재해 예방 대책 강화',
    content: '고용노동부는 외국인 근로자의 산업재해 예방을 위한 다국어 안전 교육 자료를 확대 보급한다.',
    summary: '외국인 근로자 산업재해 예방을 위한 다국어 안전교육이 강화된다.',
    url: 'https://www.kosha.or.kr/kosha/business/foreignerSafety.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '산업재해·안전',
    keywords: '외국인근로자,산업재해,안전교육',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(5, 0),
  },
  {
    title: '온열 질환 예방 가이드라인 개정 – 야외 작업 기준 강화',
    content: '고용노동부는 기후변화에 대응한 야외 작업 환경 온열 질환 예방 가이드라인을 개정했다.',
    summary: '폭염 시 야외 작업 중지 기준을 강화하는 온열 질환 예방 가이드라인이 개정됐다.',
    url: 'https://www.kosha.or.kr/kosha/data/hwCodeList.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '직업보건·화학',
    keywords: '온열질환,폭염,야외작업,가이드라인',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(5, 4),
  },
  {
    title: '위험성평가 제도 개선 방향 발표',
    content: '고용노동부는 사업장 자율 안전보건 활동을 강화하기 위한 위험성평가 제도 개선 방향을 발표했다.',
    summary: '위험성평가 제도 개선으로 사업장 자율 안전보건 활동이 강화된다.',
    url: 'https://www.moel.go.kr/news/enews/report/enewsView.do',
    source: '고용노동부',
    source_category: '정부기관',
    category: '산업재해·안전',
    keywords: '위험성평가,안전보건,제도개선',
    author: '고용노동부',
    image_url: null,
    published_at: getRecentDate(6, 0),
  },
  {
    title: '중대재해처벌법 적용 사례 분석 및 시사점',
    content: '검찰과 법원이 중대재해처벌법 적용 사례를 분석한 결과 경영책임자의 안전보건 의무 이행 실태가 주요 판단 기준으로 작용하고 있는 것으로 나타났다.',
    summary: '중대재해처벌법 적용 사례에서 경영책임자의 의무 이행이 핵심 판단 기준으로 확인됐다.',
    url: 'https://www.law.go.kr/lsSc.do?menuId=1&subMenuId=15&tabMenuId=81&query=%EC%A4%91%EB%8C%80%EC%9E%AC%ED%95%B4%EC%B2%98%EB%B2%8C%EB%B2%95',
    source: '법제처(중대재해)',
    source_category: '법령',
    category: '중대재해',
    keywords: '중대재해처벌법,판례,경영책임자',
    author: '법제처',
    image_url: null,
    published_at: getRecentDate(6, 3),
  },
  {
    title: '고압가스 취급 안전 매뉴얼 개정판 배포',
    content: '안전보건공단은 고압가스 취급 과정의 사고를 예방하기 위한 안전 매뉴얼 개정판을 제작·배포한다.',
    summary: '안전보건공단이 고압가스 취급 안전 매뉴얼 개정판을 배포한다.',
    url: 'https://www.kosha.or.kr/kosha/data/guideList.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '직업보건·화학',
    keywords: '고압가스,사고예방,매뉴얼,KOSHA',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(7, 1),
  },
  {
    title: '산업안전보건 연구원 2026년 연구과제 공모',
    content: '산업안전보건연구원은 2026년도 위탁 연구과제를 공모한다고 밝혔다.',
    summary: '산업안전보건연구원 2026년 위탁 연구과제 공모가 시작됐다.',
    url: 'https://www.kosha.or.kr/kosha/research/researchCons.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '기관동향',
    keywords: '산업안전보건연구원,연구과제,공모',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(7, 5),
  },
  {
    title: '석면 해체·제거 작업 관리 강화 방안',
    content: '고용노동부는 석면 해체·제거 작업 중 발생할 수 있는 근로자의 건강 피해를 예방하기 위한 관리 강화 방안을 발표했다.',
    summary: '석면 해체·제거 작업 시 근로자 건강 보호를 위한 관리 강화 방안이 마련됐다.',
    url: 'https://www.kosha.or.kr/kosha/business/asbestosRm.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '직업보건·화학',
    keywords: '석면,해체제거,직업병,건강보호',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(8, 0),
  },
  {
    title: '2026년 안전보건 정책 방향 – 예방 중심 체계 강화',
    content: '고용노동부는 2026년 안전보건 정책 방향을 예방 중심으로 전환하고 사업장 자율 안전보건 관리 역량을 강화하는 방향으로 추진한다고 발표했다.',
    summary: '2026년 안전보건 정책이 예방 중심으로 전환되고 사업장 자율 역량 강화에 집중된다.',
    url: 'https://www.korea.kr/news/policyNewsView.do?newsId=148929000',
    source: '정책브리핑',
    source_category: '정부기관',
    category: '정책·브리핑',
    keywords: '안전보건정책,예방,2026,고용노동부',
    author: '정책브리핑',
    image_url: null,
    published_at: getRecentDate(8, 4),
  },
  {
    title: '사업장 내 심리적 외상 예방 및 지원 방안',
    content: '안전보건공단은 사업장 내 근로자의 심리적 외상(트라우마) 예방과 지원을 위한 가이드라인을 배포했다.',
    summary: '근로자 심리적 외상 예방 및 지원을 위한 사업장 가이드라인이 배포됐다.',
    url: 'https://www.kosha.or.kr/kosha/business/mentalHealthList.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '직업보건·화학',
    keywords: '심리적외상,트라우마,근로자,직업보건',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(9, 0),
  },
  {
    title: '건설업 기초안전보건교육 이수 의무화 현황',
    content: '고용노동부는 건설업 기초안전보건교육 이수 의무화 시행 이후 현황을 발표하며, 이수율이 전년 대비 크게 향상됐다고 밝혔다.',
    summary: '건설업 기초안전보건교육 이수율이 의무화 시행 이후 크게 향상됐다.',
    url: 'https://www.kosha.or.kr/kosha/business/constructEdu.do',
    source: '안전보건공단',
    source_category: '기관',
    category: '산업재해·안전',
    keywords: '건설업,기초안전교육,의무화,이수율',
    author: '안전보건공단',
    image_url: null,
    published_at: getRecentDate(9, 3),
  },
];

function insertSampleData() {
  const count = db.prepare('SELECT COUNT(*) as cnt FROM articles').get();
  if (count.cnt > 0) {
    console.log(`[샘플데이터] 기존 데이터 ${count.cnt}건 존재, 샘플 추가 건너뜀`);
    return;
  }

  let inserted = 0;
  for (const article of sampleArticles) {
    try {
      const result = insertArticle.run(article);
      if (result.changes > 0) inserted++;
    } catch (e) {}
  }
  console.log(`[샘플데이터] ${inserted}건 삽입 완료`);
}

module.exports = { insertSampleData };
